### ISSUE TITLE
gristle_profiler fails with piped data without clear message

### ISSUE THREAD

**Issue by kenfar** [kenfar/DataGristle#129]
gristle_profiler doesn't support piped files, but it should produce a better error message to make this more clear.

$ cat data/7x7.csv | gristle_profiler -d '|' -q quote_none --has-no-header 
Traceback (most recent call last):
  File "/home/kenfar/Envs/datagristle_38_install/.venv/bin/gristle_profiler", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/kenfar/Envs/datagristle_38_install/.venv/src/datagristle/scripts/gristle_profiler", line 669, in <module>
    sys.exit(main())
  File "/home/kenfar/Envs/datagristle_38_install/.venv/src/datagristle/scripts/gristle_profiler", line 228, in main
    my_file.analyze_file()
  File "/home/kenfar/Envs/datagristle_38_install/.venv/src/datagristle/datagristle/file_type.py", line 54, in analyze_file
    if os.path.getsize(self.fqfn) == 0:
  File "/home/kenfar/.pyenv/versions/3.8.9/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '-'

**Comment by kenfar** [comment]
fixed
