### ISSUE TITLE
gristle_freaker msg on wrong file name

### ISSUE THREAD

**Issue by kenfar** [kenfar/DataGristle#137]
This should provide a clear abort msg instead of a traceback

$ gristle_freaker --config-fn example-21.yml --outfile -
Traceback (most recent call last):
  File "../../scripts/gristle_freaker", line 502, in <module>
    sys.exit(main())
  File "../../scripts/gristle_freaker", line 126, in main
    nconfig, _ = config_manager.get_config()
  File "datagristle/configulator.py", line 197, in get_config
    self.extend_config()
  File "../../scripts/gristle_freaker", line 486, in extend_config
    self.generate_csv_dialect_config()
  File "datagristle/configulator.py", line 353, in generate_csv_dialect_config
    autodetected = csvhelper.get_dialect(infiles=self.config['infiles'],
  File "datagristle/csvhelper.py", line 131, in get_dialect
    if os.path.getsize(infile) > 0:
  File "lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'examples/gristle_freaker/example-21-single_col_input.csv'

**Comment by kenfar** [comment]
fixed
