### ISSUE TITLE
gristle_profiler: fails to catch type exception

### ISSUE THREAD

**Issue by kenfar** [kenfar/DataGristle#154]
This should be caught and handle gracefully.

File Analysis Results:
  field count         16
  record count        157719
  has_header          True
  delimiter           [space]
  skipinitialspace    False
  quoting             QUOTE_NONE
  doublequote         False
  quotechar           "
  lineterminator      '\n'
  escapechar          None

Traceback (most recent call last):
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 695, in <module>
    sys.exit(main())
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 256, in main
    nconfig.read_limit)
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/field_determinator.py", line 157, in analyze_fields
    self.field_max[f_no] = miscer.get_max(self.field_types[f_no], field_freqs)
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/field_misc.py", line 250, in get_max
    maximum = str(max([transform(x[0]) for x in values if not typer.is_unknown(x[0])]))
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by kenfar** [comment]
Was not able to reproduce, may have been addressed already through other changes.
