### ISSUE TITLE
gristle_profiler - type error in field_misc

### ISSUE THREAD

**Issue by kenfar** [kenfar/DataGristle#173]
Traceback (most recent call last):
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 695, in <module>
    sys.exit(main())
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 256, in main
    nconfig.read_limit)
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/field_determinator.py", line 157, in analyze_fields
    self.field_max[f_no] = miscer.get_max(self.field_types[f_no], field_freqs)
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/field_misc.py", line 250, in get_max
    maximum = str(max([transform(x[0]) for x in values if not typer.is_unknown(x[0])]))
TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

This just needs a catch for the TypeError and return None

**Comment by kenfar** [comment]
also happens with the min function in the same module

**Comment by kenfar** [comment]
fixed
