### ISSUE TITLE
quote_nonnumeric crashes with header record

### ISSUE THREAD

**Issue by kenfar** [kenfar/DataGristle#174]
Traceback (most recent call last):
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 695, in <module>
    sys.exit(main())
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 220, in main
    nconfig, _ = config_manager.get_config()
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/configulator.py", line 197, in get_config
    self.extend_config()
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/bin/gristle_profiler", line 673, in extend_config
    self.generate_csv_header_config()
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/configulator.py", line 392, in generate_csv_header_config
    header.load_from_files(self.config['infiles'], self.config['dialect'])
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/csvhelper.py", line 122, in load_from_files
    self.load_from_file(file_name, dialect)
  File "/Users/kennethfarmer/.local/share/virtualenvs/analysis-ufrYier_/lib/python3.7/site-packages/datagristle/csvhelper.py", line 75, in load_from_file
    for field_names in reader:
ValueError: could not convert string to float: 'PHARMACY_NCPDP'

**Comment by kenfar** [comment]
Cannot reproduce - probably been fixed by other changes.
